name: CD (Continuous Delivery)

on:
  push:
    branches: ["master"]

jobs:
  build-push:
    name: Build and Push Image To DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push flaskapp
        uses: docker/build-push-action@v4
        with:
          context: ./app
          file: ./app/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:${{ github.run_number }}

      - name: Build and push postgres
        uses: docker/build-push-action@v4
        with:
          context: ./postgres
          file: ./postgres/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/postgres:${{ github.run_number }}

      - name: Debug Docker Output
        run: |
          echo "Docker Info:"
          docker info
          echo "Docker Images:"
          docker images
          echo "Docker Containers:"
          docker ps -a
          echo "Docker Buildx:"
          docker buildx ls
